# Generated by Django 4.2.6 on 2023-10-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_reporter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Headline',
            new_name='Article',
        ),
    ]
